// Generated by CoffeeScript 1.11.1
(function() {
  var Main_coffee;

  Main_coffee = (function() {
    var vm;

    function Main_coffee() {}

    vm = new Vue({
      el: 'main',
      data: {
        nuevaTarea: null,
        tareas: ['graffitar', 'programar']
      },
      methods: {
        agregarTarea: function() {
          this.tareas.push(this.nuevaTarea);
          return this.nuevaTarea = null;
        }
      }
    });

    return Main_coffee;

  })();

}).call(this);
