// Generated by CoffeeScript 1.11.1
(function() {
  var vm;

  vm = new Vue({
    el: 'main',
    data: {
      newTarea: null,
      tareas: []
    },
    methods: {
      addNewTarea: function() {
        this.tareas.unshift(this.newTarea);
        return this.newTarea = null;
      }
    }
  });

  console.log(this.vm);

}).call(this);
